import { Center, Flex, Heading, Stack } from "@chakra-ui/react";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Flex
          width="100wh"
          height="100vh"
          justifyContent="center"
          alignItems="center"
        >
          <Stack>
            <Heading>Next-Chakra-Admin</Heading>
          </Stack>
        </Flex>
      </main>
    </>
  );
}
