import Head from "next/head";
import { WithAuth } from "../components/hoc/WithAuth";
import Layout from "../components/layout";
import Dashboard from "../dashboard";

const Home = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout headerText="Dashboard">
        <Dashboard />
      </Layout>
    </>
  );
};

export default WithAuth(Home);
